
- name: Provision E-commerce Application
  hosts: vagrant
  become: yes

  vars_files:
    - group_vars/all.yml

  roles:
    - frontend
    - backend
    - database

  collections:
    - community.docker

  tasks:   
    - name: Install Python pip
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Create Docker network for the app
      docker_network:
        name: app-net
        state: present

    - name: Run frontend container
      docker_container:
        name: frontend
        image: node:14
        state: started
        networks:
          - name: app-net
        ports:
          - "3000:3000"
        volumes:
          - "/home/Assignments/roles/frontend:/usr/src/app"
        working_dir: /usr/src/app
        command: npm start
        
    - name: Run backend container
      docker_container:
        name: yolo-backend-1
        image: sherryobuhuma/yolo-backend:v1.2.0
        state: started
        restart_policy: always
        networks:
          - name: app-net
        ports:
          - "5000:5000"
        command: npm start