---
- name: Pull image from repository
  docker_image:
    name: sherryobuhuma/yolo-backend:v1.2.0
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: yolo-backend-1
    image: sherryobuhuma/yolo-backend:v1.2.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes