---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Clone frontend repository
  git:
    repo: "https://github.com/SherryObuhuma/yolo"
    dest: "yolo/roles"
    version: "master"

- name: Run frontend container
  docker_container:
    name: frontend
    image: node:14
    state: started
    restart_policy: always
    command: npm start
    working_dir: "/usr/src/app"
    volumes:
      - "/home/Assignments/yolo/roles/frontend:/usr/src/app"
    ports:
      - "3000:3000"

