---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Clone frontend repository
  git:
    repo: "https://github.com/SherryObuhuma/yolo"
    dest: "yolo/roles"
    version: "main"

- name: Run frontend container
  docker_container:
    name: frontend
    image: node:14
    state: started
    restart_policy: always
    command: npm start
    working_dir: "yolo/roles/frontend"
    volumes:
      - "yolo/roles/frontend:/app"
    ports:
      - "3000:3000"

